### ISSUE TITLE
get new messages does not work

### ISSUE THREAD

**Issue by krille-chan** [cheio/catastrophe#1]
Like in the title ...
In my code is:
`
> XMPP.conn.roster.get(function(){
>         contactList = XMPP.conn.roster.items;
>         for(var i = 0; i < contactList.length; i++){
>                 XMPP.roster[contactJabberId]=function(from,body) { alert(from + " said: " + body);
>         }
> }
`

But I never get new messages. Also not with console.log() instead of alert().

**Comment by cheio** [comment]
fixed
